// <auto-generated />
using System;
using AspNetCoreWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreWebApi.Data.Migrations
{
    [DbContext(typeof(TreeStructureDbContext))]
    partial class TreeStructureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNetCoreWebApi.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NodeId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "example element 1a"
                        },
                        new
                        {
                            Id = 2,
                            Name = "example element 1b"
                        },
                        new
                        {
                            Id = 3,
                            Name = "example element 1c"
                        },
                        new
                        {
                            Id = 4,
                            Name = "example element 1d"
                        },
                        new
                        {
                            Id = 5,
                            Name = "example element 2a",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "example element 2b",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "example element 2c",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "example element 2d",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "example element 3a",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "example element 3b",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "example element 3c",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 12,
                            Name = "example element 3d",
                            ParentId = 7
                        });
                });

            modelBuilder.Entity("AspNetCoreWebApi.Models.Node", b =>
                {
                    b.HasOne("AspNetCoreWebApi.Models.Node", null)
                        .WithMany("Childrens")
                        .HasForeignKey("NodeId");
                });

            modelBuilder.Entity("AspNetCoreWebApi.Models.Node", b =>
                {
                    b.Navigation("Childrens");
                });
#pragma warning restore 612, 618
        }
    }
}
